Artem Makoyan, contest 17022, problem A
MakArtKar/MyHashMap pull request #1
Opened 2020-02-17 15:49 UTC by MakArtKar

https://official.contest.yandex.ru/contest/17022/run-report/30964008/

2020-02-18 10:14 UTC, SenderOK commented
Вообще вам видимо всё же нужен другой ревьювер - ваш семинарист, Глеб

Но я сходу вижу, что вы сделали пару ошибок, не относящихся к коду задачи, которые полезно поправить прежде чем начинать ревью: 
1) закоммитили бинарь в репозиторий - обычно так не делают, ибо это раздувает размер, затрудняет работу с ним всей команды, репозиторий для кода

2) в вашем PR должен быть только файл hash_map.h, ибо остальные не требуют ревью - два других файла можете сразу закоммитить в ветку master, после чего сделать новую ветку и новый PR, либо rebase на мастер для этой ветки.

2020-02-18 10:15 UTC, SenderOK commented
первые главы https://git-scm.com/book/ru/v2 вам в помощь

2020-03-15 23:22 UTC, glebshp requested changes
Надо сделать нормальные имена, отступы и пробелы, поставить комментарии у методов, тогда можно будет смотреть по существу

2020-03-15 23:22 UTC, glebshp commented on hash_map.h
> +    using iterator = typename std::list <T>::iterator;
Не стоит отбивать аргументы шаблона пробелами, т.е.
std::vector\<int\> my_vector;

2020-03-15 23:22 UTC, glebshp commented on hash_map.h
> +    std::list <T> keys;
Методы, поля и локальные переменные в хорошем style guide отличаются друг от друга по написанию, это значительно увеличивает читаемость кода

2020-03-15 23:22 UTC, glebshp commented on hash_map.h
> +    std::vector <std::vector <iterator> > mas;
mas, n - плохие имена полей

2020-03-15 23:22 UTC, glebshp commented on hash_map.h
> +        for (auto it : mas[hash_key]) {
const auto

2020-05-02 18:23 UTC, MakArtKar commented
Поправил замечания (надеюсь) из прошлого ревью. Номер посылки в ЯК: 32708764

2020-06-10 05:11 UTC, MakArtKar reviewed
Исправил замечания

2020-06-19 22:18 UTC, glebshp requested changes

2020-06-19 22:18 UTC, glebshp commented on hash_map.h
> +The implementation of hash map (hash table) using closed addressing (open hashing) and rebuilding by doubling the size of container.
Во-первых мне непонятно, что такое closed addressing + open hashing
Во-вторых не хватает слов про гарантии линейного итерирования

2020-06-19 22:18 UTC, glebshp commented on hash_map.h
> +    int Mod, Sz;
Почему int, а не uint ?

2020-06-19 22:18 UTC, glebshp commented on hash_map.h
> +    int Mod, Sz;
Одна строка - одно объявление поля

2020-06-19 22:18 UTC, glebshp commented on hash_map.h
> + private:
Почему приватные поля так высоко? Публичные методы явно интереснее для читающего код

2020-06-19 22:18 UTC, glebshp commented on hash_map.h
> +        if (++Sz >= Mod) {
Ужасно!

Увеличить размер и проверить не надо ли увеличить - два разных по смыслу действия, ни в коем случае не надо их писать в одну строчку.

Действие "проверь не пора ли увеличить таблицу и, если надо, увеличь, следует вынести в отдельный метод resize_if_needed (или что-то похожее)"

2020-06-19 22:18 UTC, glebshp commented on hash_map.h
> +    // Time: O(1).
Сделай чтобы была пустая строка между концом метода и началом коммента к следующему методу

2020-06-19 22:18 UTC, glebshp commented on hash_map.h
> +    // Time: O(1).
везде

2020-06-19 22:18 UTC, glebshp commented on hash_map.h
> +        for (auto it : LoopedContainer[hash_key]) {
const ?

2020-06-21 00:23 UTC, glebshp approved these changes

2020-06-21 00:38 UTC, merged